version: '3'
services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports: 
    - 27017:27017
    environment:
    - MONGO_INITDB_DATABASE=mongodb
    volumes:
    - ./mongo-volume:/data/db
    - ./docker-entrypoint-initdb.d/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro