server:
  port: 8080

spring:
  application:
    name: auth
  datasource:
    username: 'admin'
    password: 'password'
    url: jdbc:postgresql://localhost:5432/user
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true